### ISSUE TITLE
FR: Also support 'cards'

### ISSUE THREAD

**Issue by sandrodunkel** [vandres/craft-matrix-extended#12]
The configured groups are ignored when the matrix field's view mode is set to anything but 'As inline-editable blocks', e.g. when using 'As cards'

**Comment by vandres** [comment]
The original idea of the plugin was, to add Neo features to the native Matrix field. Therefore the focus lies on the inline-editable blocks. Nonetheless I will take a quick look, if this can also be easily achieved for the other view modes.

**Comment by vandres** [comment]
@sandrodunkel Sorry, I will not support the other view modes for now. Maybe in the future...

I will leave the ticket open for that

**Comment by sandrodunkel** [comment]
No worries! Thanks for looking into it.

**Comment by sandrodunkel** [comment]
Any updates? 🫣
Recently made the switch to mainly using cards for complex matrix blocks and I miss being able to use your plugin…

**Comment by vandres** [comment]
Good to hear, that you like using the plugin :D 

The future of that feature is far away. I simply have not the time, as I am not using cards in my own projects.

**Comment by garycrane** [comment]
Would be so good if Matrix Extended supported Cards 🙏 🙏🙏🙂

**Comment by vandres** [comment]
@garycrane @sandrodunkel 

I am using the plugin mainly for my own projects and did open source it on request of a friend. That's why the roapmap is also focused only around my project and my project starter. 

Two suggestions, and I hope, I will not offend anybody

1. I can show you where to start, so you can develop it yourself and give it back as a pull request
2. You could throw in some money and I will develop it on demand

**Comment by garycrane** [comment]
No offence taken at all. Thanks for responding. I've sent you an email with the view to exploring option 2 in a bit more detail.

**Comment by vandres** [comment]
@sandrodunkel The first, experimental, version of card support is in its own branch. Can you please give it a try and send me feedback?

`composer require vandres/craft-matrix-extended:"dev-cards as 4.0.0"`

Enable `experimentalFeatures` in plugin settings.

I will aim for a new major version, because the plugin is now working around drafts, instread of saved entries. This changes the  behaviour and I don't want to affect current users (yet)

**Comment by vandres** [comment]
Issues found (with nested Matrix):

- duplicate parent element
- change entry type within the clone
- "The owner element must be a derivitive"

**Comment by vandres** [comment]
Feedback is positive so far. I will release it on Monday

**Comment by vandres** [comment]
Released in v4.0.0

**Comment by sandrodunkel** [comment]
Sorry @vandres I haven't been able to test it last week. Will definitely update this week tho. Thanks to you and everyone involved!
